# -*- coding: utf-8 -*-
"""Dados do pacote v1 de melhorias do site (16/09/2026).

Separado da lógica (patch_v1.py) para manter o script legível.
Tudo aqui é conteúdo: traduções novas/corrigidas e as reviews reais
que substituem os depoimentos genéricos das páginas de cidade.
"""

# ── Valores corrigidos por idioma para chaves EXISTENTES ─────────────────────
# patch_v1.py substitui o valor da chave dentro do bloco de cada idioma.
CHANGED_KEYS = {
    "en": {
        "topbar_insured": "Background-checked, bonded & fully insured team",
        "services_subtitle": "Eight professional cleaning services — luxury-level attention to detail on every single visit.",
        "aeo_services": "Signature Luxury Cleaning offers eight services across Silicon Valley: Regular Cleaning, Deep Cleaning, Move In/Out, Post-Construction, Airbnb Turnover, Office Cleaning, Spring Cleaning, and the White Glove Deep Clean. All include eco-friendly products and a 100% satisfaction guarantee.",
        "aeo_areas": "We serve 22 cities across the Peninsula and Silicon Valley — from Burlingame and San Mateo down to San Jose. Most areas qualify for same-day cleaning availability. Service radius covers San Mateo County and Santa Clara County.",
        "areas_subtitle": "We serve 22 cities across Silicon Valley & Peninsula — from Burlingame to San Jose. Don't see your city? Call us — we may still be able to help.",
        "footer_desc": "Silicon Valley & Peninsula's most trusted luxury residential cleaning service. Serving Burlingame, Palo Alto, Cupertino, Mountain View, Sunnyvale & 22 cities.",
        "nav_app": "📱 See Prices & Book",
        "hero_btn_strong": "See Your Price & Book",
    },
    "zh": {
        "topbar_insured": "团队通过背景审查 · 已投保并有履约担保",
        "services_subtitle": "八项专业清洁服务 — 每次拜访都提供豪华级别的细心服务。",
        "aeo_services": "Signature Luxury Cleaning在硅谷提供八项服务：日常清洁、深度清洁、搬入/搬出清洁、施工后清洁、Airbnb周转清洁、办公室清洁、春季大扫除以及White Glove深度清洁。所有服务均使用环保产品，并提供100%满意保证。",
        "aeo_areas": "我们服务半岛和硅谷的22个城市 — 从Burlingame、San Mateo一直到San Jose。大多数地区可享受当天服务。服务范围覆盖San Mateo县和Santa Clara县。",
        "areas_subtitle": "我们服务硅谷和半岛的22个城市 — 从Burlingame到San Jose。没看到您的城市？请致电 — 我们可能仍能为您服务。",
        "nav_app": "📱 查看价格并预订",
        "hero_btn_strong": "查看您的价格并预订",
    },
    "hi": {
        "topbar_insured": "पृष्ठभूमि-जांची हुई, बॉन्डेड और पूर्ण बीमित टीम",
        "services_subtitle": "आठ पेशेवर सफाई सेवाएं — हर विजिट पर लक्जरी-स्तर का ध्यान।",
        "aeo_services": "Signature Luxury Cleaning सिलिकॉन वैली में आठ सेवाएं प्रदान करता है: नियमित सफाई, डीप क्लीनिंग, मूव इन/आउट, निर्माण के बाद की सफाई, Airbnb टर्नओवर, ऑफिस क्लीनिंग, स्प्रिंग क्लीनिंग और White Glove डीप क्लीन। सभी में इको-फ्रेंडली उत्पाद और 100% संतुष्टि की गारंटी शामिल है।",
        "aeo_areas": "हम पेनिनसुला और सिलिकॉन वैली के 22 शहरों में सेवा देते हैं — Burlingame और San Mateo से लेकर San Jose तक। अधिकांश क्षेत्रों में उसी दिन सेवा उपलब्ध है। सेवा क्षेत्र San Mateo काउंटी और Santa Clara काउंटी को कवर करता है।",
        "areas_subtitle": "हम सिलिकॉन वैली और पेनिनसुला के 22 शहरों में सेवा देते हैं। अपना शहर नहीं दिखा? हमें कॉल करें।",
        "nav_app": "📱 कीमत देखें और बुक करें",
        "hero_btn_strong": "अपनी कीमत देखें और बुक करें",
    },
    "tl": {
        "topbar_insured": "Background-checked, bonded at fully insured na team",
        "services_subtitle": "Walong propesyonal na serbisyo sa paglilinis — luxury-level na atensyon sa bawat detalye, sa bawat bisita.",
        "aeo_services": "Nag-aalok ang Signature Luxury Cleaning ng walong serbisyo sa Silicon Valley: Regular Cleaning, Deep Cleaning, Move In/Out, Post-Construction, Airbnb Turnover, Office Cleaning, Spring Cleaning, at ang White Glove Deep Clean. Kasama sa lahat ang eco-friendly na produkto at 100% satisfaction guarantee.",
        "aeo_areas": "Naglilingkod kami sa 22 lungsod sa Peninsula at Silicon Valley — mula Burlingame at San Mateo hanggang San Jose. Karamihan sa mga lugar ay maaaring ma-serbisyuhan sa parehong araw. Sakop ang San Mateo County at Santa Clara County.",
        "areas_subtitle": "Naglilingkod kami sa 22 lungsod sa Silicon Valley at Peninsula — mula Burlingame hanggang San Jose. Hindi mo nakita ang lungsod mo? Tawagan kami.",
        "nav_app": "📱 Tingnan ang Presyo at Mag-book",
        "hero_btn_strong": "Tingnan ang Presyo Mo at Mag-book",
    },
    "vi": {
        "topbar_insured": "Đội ngũ đã kiểm tra lý lịch, có bảo lãnh & bảo hiểm đầy đủ",
        "services_subtitle": "Tám dịch vụ vệ sinh chuyên nghiệp — chăm chút từng chi tiết đẳng cấp sang trọng trong mỗi lần ghé thăm.",
        "aeo_services": "Signature Luxury Cleaning cung cấp tám dịch vụ tại Silicon Valley: Vệ sinh định kỳ, Vệ sinh sâu, Dọn vào/dọn ra, Sau xây dựng, Airbnb Turnover, Văn phòng, Tổng vệ sinh mùa xuân và White Glove Deep Clean. Tất cả đều dùng sản phẩm thân thiện môi trường và bảo đảm hài lòng 100%.",
        "aeo_areas": "Chúng tôi phục vụ 22 thành phố khắp Peninsula và Silicon Valley — từ Burlingame, San Mateo đến San Jose. Hầu hết khu vực có thể phục vụ trong ngày. Phạm vi bao gồm quận San Mateo và Santa Clara.",
        "areas_subtitle": "Chúng tôi phục vụ 22 thành phố tại Silicon Valley & Peninsula — từ Burlingame đến San Jose. Không thấy thành phố của bạn? Hãy gọi cho chúng tôi.",
        "nav_app": "📱 Xem giá & Đặt lịch",
        "hero_btn_strong": "Xem giá của bạn & Đặt lịch",
    },
    "ko": {
        "topbar_insured": "신원 조회 완료 · 보증(bonded) · 완전 보험 가입 팀",
        "services_subtitle": "8가지 전문 청소 서비스 — 방문할 때마다 럭셔리 수준의 세심함.",
        "aeo_services": "Signature Luxury Cleaning은 실리콘밸리에서 8가지 서비스를 제공합니다: 정기 청소, 정밀 청소, 입주/퇴거 청소, 공사 후 청소, Airbnb 턴오버, 사무실 청소, 봄맞이 청소, White Glove 정밀 청소. 모든 서비스에 친환경 제품과 100% 만족 보장이 포함됩니다.",
        "aeo_areas": "반도와 실리콘밸리 전역 22개 도시에 서비스를 제공합니다 — Burlingame, San Mateo부터 San Jose까지. 대부분 지역 당일 서비스 가능. San Mateo 카운티와 Santa Clara 카운티 전역을 커버합니다.",
        "areas_subtitle": "실리콘밸리와 반도 전역 22개 도시에 서비스를 제공합니다 — Burlingame부터 San Jose까지. 도시가 안 보이나요? 전화 주세요.",
        "nav_app": "📱 가격 확인 & 예약",
        "hero_btn_strong": "내 가격 확인하고 예약하기",
    },
}

# Trocas dentro do <strong> dos botões compostos (cta_btn, app_btn, hero_btn_app)
STRONG_SWAP = {
    "en": ("Open Our App", "See Your Price & Book"),
    "zh": ("打开应用", "查看价格并预订"),
    "hi": ("ऐप खोलें", "कीमत देखें और बुक करें"),
    "tl": ("Buksan ang App", "Tingnan ang Presyo at Mag-book"),
    "vi": ("Mở Ứng Dụng", "Xem giá & Đặt lịch"),
    "ko": ("앱 열기", "가격 확인하고 예약"),
}

# Preços defasados nas chaves svcN_price (número antigo → novo, em todos os idiomas)
PRICE_FIXES = {
    "svc2_price": ("220", "270"),
    "svc3_price": ("220", "330"),
    "svc5_price": ("150", "155"),
    "svc6_price": ("270", "410"),
}

# ── Chaves NOVAS (todas as línguas) ──────────────────────────────────────────
NEW_KEYS = {
    "en": {
        "hero_prices_note": "Exact price for your home in the app — takes 60 seconds.",
        "ba_title": "Before &amp; After — real jobs, documented by our own team",
        "ba_cap1": "Behind the stove — White Glove Deep Clean",
        "ba_cap2": "Under &amp; behind the refrigerator",
        "ba_cap3": "Shower &amp; tile restoration",
    },
    "zh": {
        "hero_prices_note": "在应用中查看您家的确切价格 — 只需60秒。",
        "ba_title": "清洁前后对比 — 我们团队记录的真实案例",
        "ba_cap1": "炉灶后方 — White Glove深度清洁",
        "ba_cap2": "冰箱底部与后方",
        "ba_cap3": "淋浴间与瓷砖焕新",
    },
    "hi": {
        "hero_prices_note": "ऐप में अपने घर की सटीक कीमत देखें — सिर्फ 60 सेकंड।",
        "ba_title": "पहले और बाद — हमारी टीम द्वारा दर्ज वास्तविक काम",
        "ba_cap1": "चूल्हे के पीछे — White Glove डीप क्लीन",
        "ba_cap2": "फ्रिज के नीचे और पीछे",
        "ba_cap3": "शॉवर और टाइल की चमक बहाल",
    },
    "tl": {
        "hero_prices_note": "Eksaktong presyo para sa bahay mo sa app — 60 segundo lang.",
        "ba_title": "Before &amp; After — totoong trabaho, dokumentado ng team namin",
        "ba_cap1": "Sa likod ng kalan — White Glove Deep Clean",
        "ba_cap2": "Ilalim at likod ng refrigerator",
        "ba_cap3": "Shower at tile restoration",
    },
    "vi": {
        "hero_prices_note": "Giá chính xác cho nhà bạn trong ứng dụng — chỉ 60 giây.",
        "ba_title": "Trước &amp; Sau — công việc thật, do chính đội chúng tôi ghi lại",
        "ba_cap1": "Phía sau bếp — White Glove Deep Clean",
        "ba_cap2": "Dưới và sau tủ lạnh",
        "ba_cap3": "Phục hồi vòi sen &amp; gạch men",
    },
    "ko": {
        "hero_prices_note": "앱에서 우리 집 정확한 가격 확인 — 60초면 됩니다.",
        "ba_title": "비포 &amp; 애프터 — 저희 팀이 직접 기록한 실제 작업",
        "ba_cap1": "레인지 뒤편 — White Glove 정밀 청소",
        "ba_cap2": "냉장고 아래·뒤편",
        "ba_cap3": "샤워부스·타일 복원",
    },
}

# ── Dicionário japonês completo (anúncios agora rodam para japonês) ─────────
JA_DICT = {
    "topbar_discount": "✨ 新規のお客様は定期サービスで毎回最大15%オフ — 毎週−15%、隔週−10%",
    "topbar_call": "電話・SMS：",
    "topbar_offer": "新規のお客様は定期サービスで毎回最大15%オフ — 毎週−15%、隔週−10%",
    "topbar_phone": "電話・SMS：<span class='accent'>(650) 619-3504</span>",
    "topbar_products": "プロ仕様の洗剤と機材",
    "topbar_rating": "<span class='accent'>5.0★</span> Googleレビュー満点評価",
    "topbar_insured": "身元調査済み・身元保証・保険完備のチーム",
    "topbar_app": "ダウンロード不要 — どのスマホでもアプリを開けます",
    "nav_services": "サービス",
    "nav_how": "ご利用の流れ",
    "nav_why": "選ばれる理由",
    "nav_reviews": "お客様の声",
    "nav_areas": "対応エリア",
    "nav_phone": "📞 (650) 619-3504",
    "nav_app": "📱 料金を見る・予約",
    "hero_badge": "📍 シリコンバレー＆ペニンシュラ対応",
    "hero_title": "あなたの時間を取り戻す。<br><em>帰る家は、いつも輝く我が家へ。</em>",
    "hero_subtitle": "シリコンバレー＆ペニンシュラで最も信頼されるラグジュアリー清掃サービス。大切なことに集中できるよう、私たちがご自宅をお手入れします。",
    "hero_slots": "⚡ 今週の空き枠はわずかです",
    "hero_btn_app": "<small>60秒で予約</small><strong>料金を見て予約する</strong>",
    "hero_btn_phone": "📞 (650) 619-3504",
    "hero_stat_families": "清掃実績",
    "hero_stat_rating": "Google評価",
    "hero_stat_cities": "対応都市",
    "hero_btn_small": "ダウンロード不要 — どのスマホでも使えます",
    "hero_btn_strong": "料金を見て予約する",
    "hero_prefer_call": "お電話をご希望ですか？",
    "hero_prices_note": "アプリでご自宅の正確な料金を確認 — 60秒で完了。",
    "mockup_greeting": "おはようございます、",
    "mockup_welcome": "おかえりなさい！",
    "mockup_services": "サービス一覧",
    "mockup_book": "今すぐ予約 — アプリで安全に決済",
    "badge_rating": "5.0 — 満点評価",
    "badge_booking": "予約確定！",
    "svc_regular": "定期清掃",
    "svc_deep": "ディープ",
    "svc_moveout": "退去清掃",
    "trust_licensed": "許認可・保険完備",
    "trust_background": "身元調査済みチーム",
    "trust_eco": "環境にやさしい洗剤",
    "trust_guarantee": "100%満足保証",
    "trust_app": "アプリで予約・決済",
    "services_label": "サービス",
    "services_title": "SLCが提供する<br><em>清掃サービスとは？</em>",
    "aeo_services": "Signature Luxury Cleaningはシリコンバレーで8つのサービスを提供：定期清掃、ディープクリーニング、入居/退去清掃、施工後清掃、Airbnbターンオーバー、オフィス清掃、スプリングクリーニング、White Glove Deep Clean。すべて環境にやさしい洗剤と100%満足保証付きです。",
    "services_subtitle": "8つのプロフェッショナル清掃サービス — 毎回、ラグジュアリー水準の丁寧さで。",
    "badge_popular": "⭐ 一番人気",
    "svc1_title": "定期清掃",
    "svc1_desc": "毎週・隔週・毎月のメンテナンス清掃。ご希望のスケジュールで、いつも清潔なご自宅を。",
    "svc1_i1": "全室の掃除機がけ・モップがけ",
    "svc1_i2": "キッチン・バスルームの除菌",
    "svc1_i3": "各所の拭き掃除・ホコリ取り",
    "svc1_i4": "ベッドメイキング・リネン交換",
    "svc1_price": "$170〜",
    "svc_cta": "アプリで予約 →",
    "svc2_title": "ディープクリーニング",
    "svc2_desc": "上から下まで徹底清掃 — 家電の内部、キャビネット、巾木まで隅々と。",
    "svc2_i1": "オーブン・冷蔵庫・電子レンジの内部",
    "svc2_i2": "キャビネット・引き出しの内部",
    "svc2_i3": "巾木・窓枠",
    "svc2_i4": "目地・タイルの磨き上げ",
    "svc2_price": "$270〜",
    "svc3_title": "入居・退去清掃",
    "svc3_desc": "敷金の全額返還を目指して。すべての面・収納・家電を徹底的に清掃します。",
    "svc3_i1": "物件全体のディープクリーニング",
    "svc3_i2": "全家電の内部清掃",
    "svc3_i3": "壁の部分清掃",
    "svc3_i4": "敷金返還保証",
    "svc3_price": "$330〜",
    "svc4_title": "施工後清掃",
    "svc4_desc": "リフォームや工事の後の粉塵・残材を専門的に除去します。",
    "svc4_i1": "工事粉塵の除去",
    "svc4_i2": "残材・付着物の清掃",
    "svc4_i3": "窓・表面の磨き上げ",
    "svc4_i4": "最終確認の立ち会い",
    "svc4_price": "お見積り",
    "svc5_title": "Airbnbターンオーバー",
    "svc5_desc": "スピーディーで確実なターンオーバー。リネン交換と全体清掃で、いつでもゲストを迎えられる状態に。",
    "svc5_i1": "ゲスト入れ替え時の全体清掃",
    "svc5_i2": "清潔なリネン・タオル",
    "svc5_i3": "備品の補充",
    "svc5_i4": "写真映えする仕上がり",
    "svc5_price": "$155〜",
    "svc6_title": "スプリングクリーニング",
    "svc6_desc": "年に一度の徹底リフレッシュ — 片付けのお手伝い、全室のディープクリーニング、窓掃除など。",
    "svc6_i1": "家全体のディープクリーニング",
    "svc6_i2": "窓の内外清掃",
    "svc6_i3": "片付けのお手伝い",
    "svc6_i4": "ガレージ・収納スペース",
    "svc6_price": "$410〜",
    "svc_whiteglove_title": "White Glove Deep Clean",
    "svc_whiteglove_desc": "当社最高峰の清掃サービス。2名のチームが冷蔵庫・コンロ・洗濯機・乾燥機・ソファ・ベッドを実際に動かし、隠れた面まで徹底清掃。ビフォー/アフターの写真記録付き。",
    "svc_btn_book": "アプリで予約 →",
    "svc_btn_quote": "お見積りはお電話で →",
    "app_label": "アプリ",
    "app_title": "SLC予約アプリは<br><em>どう使うの？</em>",
    "aeo_how": "ウェブアプリから60秒で予約：サービスを選び、頻度を選択、日時を指定、住所を確認。決済はStripe。チームが伺い、サービス後はご一緒に仕上がりを確認します。",
    "aeo_how2": "ウェブアプリから60秒で予約：サービスを選び、頻度を選択、日時を指定、住所を確認。決済はStripe。チームが伺い、サービス後はご一緒に仕上がりを確認します。",
    "app_subtitle": "電話も待ち時間も不要。アプリを開けば、清掃スケジュールをいつでもどこでも自由に管理できます。",
    "app_f1_title": "その場で予約",
    "app_f1_desc": "サービス・日付・時間を60秒以内で選択。空き状況はリアルタイム、やり取りは不要です。",
    "app_f2_title": "安全な決済",
    "app_f2_desc": "クレジット、デビット、Apple Payで安全にお支払い。領収書は毎回自動送信されます。",
    "app_f3_title": "リアルタイム通知",
    "app_f3_desc": "チームの出発時、到着時、作業完了時にお知らせします。",
    "app_f4_title": "評価とレビュー",
    "app_f4_desc": "毎回の訪問後にフィードバックを。お客様の満足が品質の原動力です — 保証付き。",
    "app_btn": "<small>iPhone・Android対応</small><strong>料金を見て予約する</strong>",
    "pwa_small": "App Store不要",
    "pwa_strong": "アプリを開く",
    "pwa_steps_title": "ホーム画面への追加方法：",
    "pwa_s1_title": "リンクを開く",
    "pwa_s1_desc": "スマホで上のボタンをタップ",
    "pwa_s2_title": "共有/メニューをタップ",
    "pwa_s2_desc": "iPhone：共有↑ | Android：⋮メニュー",
    "pwa_s3_title": "ホーム画面に追加",
    "pwa_s3_desc": "「ホーム画面に追加」をタップ — 完了！アプリのように使えます。",
    "pwa_step1_ios": "iPhone：共有 → ホーム画面に追加",
    "pwa_step2_android": "Android：メニュー → ホーム画面に追加",
    "pwa_step3": "完了！ネイティブアプリのように使えます",
    "how_label": "ご利用の流れ",
    "how_title": "ご予約の流れは<br><em>どうなっていますか？</em>",
    "how_subtitle": "予約からきれいな我が家まで — 所要時間はわずか2分。",
    "how_s1_title": "アプリを開く",
    "how_s1_desc": "ダウンロード不要。スマホでリンクを開くだけ — iPhoneもAndroidも即対応。",
    "how_s2_title": "サービスを選ぶ",
    "how_s2_desc": "サービスを見て、明朗な料金を確認し、ご都合の良い日時を選択。",
    "how_s3_title": "私たちが清掃",
    "how_s3_desc": "身元調査済みのチームが機材一式を持って時間通りに伺います。ご在宅は不要です。",
    "how_s4_title": "我が家を満喫",
    "how_s4_desc": "ピカピカで良い香りの我が家へ。アプリで評価を — 毎回保証付き。",
    "why_badge_title": "満足保証",
    "why_badge_desc": "お客様が確認 — 退出前に手直しします",
    "why_label": "選ばれる理由",
    "why_title": "大手ハウスクリーニングではなく<br><em>Signatureを選ぶ理由は？</em>",
    "aeo_why": "Signature Luxury Cleaningは2023年からオーナー自らが運営。フランチャイズでもコールセンターでもありません。すべてのやり取りはオーナーに直接届きます。スタッフ全員が身元調査済み・身元保証付きで、オーナーが直接研修。賠償責任保険も完備しています。",
    "why_intro": "長時間働いて、散らかった家に帰る辛さを私たちは知っています。夜の時間も、週末も、心の余裕も取り戻していただく — それが私たちの存在理由です。",
    "why_p1_title": "環境にやさしい洗剤",
    "why_p1_desc": "無毒・植物由来・生分解性 — お子様にもペットにも地球にも安心。",
    "why_p2_title": "細部にこだわるチーム",
    "why_p2_desc": "すべての角、すべての面、毎回の訪問 — 最高水準で清掃。手抜きは一切ありません。",
    "why_p3_title": "許認可・身元保証・保険完備",
    "why_p3_desc": "カリフォルニア州で身元保証・保険完備。スタッフ全員が採用前に身元調査を受けています。",
    "why_p4_title": "100%満足保証",
    "why_p4_desc": "作業後、お客様ご自身で全箇所をご確認ください。ご満足いただけない点があれば、その場で退出前に手直しします。お客様の承認が私たちの基準です。",
    "why_p5_title": "アプリで完全管理",
    "why_p5_desc": "予約、変更、支払い、チームへの連絡 — すべて手のひらの中で。",
    "gallery_label": "施工事例",
    "gallery_title": "シリコンバレーで<br><em>どんな家を清掃してきた？</em>",
    "gallery_subtitle": "シリコンバレー＆ペニンシュラの実際のご自宅での実例です。",
    "ba_title": "ビフォー &amp; アフター — 当チームが記録した実際の作業",
    "ba_cap1": "コンロの裏側 — White Glove Deep Clean",
    "ba_cap2": "冷蔵庫の下と裏側",
    "ba_cap3": "シャワー・タイルの復元",
    "reviews_label": "お客様の声",
    "reviews_title": "シリコンバレーの皆様の<br><em>ご評価は？</em>",
    "aeo_reviews": "Signature Luxury CleaningはGoogleで5.0★評価。Palo Alto、Mountain View、Cupertino、Belmont、Burlingameのお客様からレビューをいただいています。安定した品質、プロ意識、プライバシーへの配慮が高く評価されています。",
    "reviews_count": "シリコンバレー＆ペニンシュラの数百のご家庭にご利用いただいています",
    "rev1_text": "「Palo Altoで4社試しましたが、Signatureがダントツです。丁寧でプロフェッショナル、毎回家中が良い香りになります。」",
    "rev2_text": "「退去清掃をお願いして敷金$3,200が全額戻ってきました！思いもよらない所まで清掃してくれて、価格以上の価値があります。」",
    "rev3_text": "「4ベッドルームの家を3時間で完璧に仕上げてくれました。礼儀正しく、速く、驚くほど丁寧。利用して8か月になります。」",
    "rev4_text": "「両親が来る前にディープクリーニングを依頼。母が『今まで見た中で一番きれい』と言ったのがすべてを物語っています！来月もお願いします。」",
    "rev5_text": "「シリコンバレーで最高の清掃サービス。1年以上毎週利用していますが、品質が落ちたことは一度もありません。」",
    "rev6_text": "「全面リフォーム後の施工後清掃 — 粉塵も残材も完璧に除去。家が新築のようになりました。チーム全員の素晴らしい仕事です。」",
    "areas_label": "対応エリア",
    "areas_title": "シリコンバレーの<br><em>どの都市に対応？</em>",
    "aeo_areas": "ペニンシュラとシリコンバレーの22都市に対応 — BurlingameやSan MateoからSan Joseまで。多くのエリアで当日対応が可能です。San Mateo郡とSanta Clara郡をカバーしています。",
    "areas_subtitle": "シリコンバレー＆ペニンシュラの22都市に対応 — BurlingameからSan Joseまで。お住まいの都市がない場合はお電話ください — 対応できる場合があります。",
    "trust_title": "ご家族に信頼される理由<br><em>Signature Luxury Cleaning</em>",
    "cta_label": "📱 さあ、始めましょう",
    "cta_title": "ピカピカの我が家、<br><em>始めませんか？</em>",
    "cta_subtitle": "新規のお客様は定期サービスで毎回最大15%オフ — 毎週−15%、隔週−10%。アプリを開いて60秒で予約 — ダウンロード不要。",
    "cta_btn": "<small>iPhone・Android対応</small><strong>料金を見て予約する</strong>",
    "cta_or": "またはお電話で：",
    "cta_or_call": "またはお電話で：<a href='tel:6506193504' style='color:var(--gold-light);'>(650) 619-3504</a>",
    "pwa_cta_small": "iPhone・Android対応",
    "footer_desc": "シリコンバレー＆ペニンシュラで最も信頼されるラグジュアリー住宅清掃サービス。Burlingame、Palo Alto、Cupertino、Mountain View、Sunnyvaleなど22都市に対応。",
    "footer_services": "サービス",
    "footer_company": "会社情報",
    "footer_about": "私たちについて",
    "footer_faq": "よくある質問",
    "footer_careers": "採用情報",
    "footer_contact": "お問い合わせ",
    "footer_areas": "対応エリア",
    "footer_app": "📱 アプリを開く",
    "footer_privacy": "プライバシーポリシー",
    "footer_copy": "© 2026 Signature Luxury Cleaning. All rights reserved.",
    "footer_love": "シリコンバレー＆ペニンシュラに真心を込めて ❤️",
}

# ── Reviews reais (as mesmas do Google que já estão na home) ─────────────────
REAL_REVIEWS = [
    ("Harshita S.", "I've tried 4 different services in Palo Alto and Signature is BY FAR the best. They're thorough, professional, and the house smells amazing after every visit."),
    ("Danillo R.", "Booked a move-out clean and got my full deposit back — $3,200! They cleaned things I didn't even think about. Worth every single penny."),
    ("Renata S.", "I have a 4-bedroom home and they finished in 3 hours perfectly. The team was polite, fast, and incredibly detailed. I've been a client for 8 months."),
    ("Alday C.", "Deep cleaning before my parents visited. My mom said it was the cleanest she'd ever seen my house. That says everything! Booking again next month."),
    ("Karla S.", "Best cleaning service in Silicon Valley, period. I've been a weekly client for over a year and the quality never drops. Highly recommend to everyone."),
    ("Mia", "Post-construction cleaning after our full remodel — they removed all the dust and debris perfectly. The house looked brand new. Incredible job by the whole team."),
]

# Preços que entram nos cards da home (ordem: regular, deep, move, postc, airbnb, office, spring)
HOME_CARD_PRICES = [
    ("svc1_title", "From <strong>$170</strong>", None),
    ("svc2_title", "From <strong>$270</strong>", None),
    ("svc3_title", "From <strong>$330</strong>", None),
    ("svc4_title", "<strong>Custom Quote</strong>", None),
    ("svc5_title", "From <strong>$155</strong>", None),
    (None, None, None),  # office: card sem data-i18n no título — tratado por âncora própria
    ("svc6_title", "From <strong>$410</strong>", None),
]
